<a href="https://colab.research.google.com/github/segasai/mapping_the_galaxy_course_cmu/blob/master/notebooks/Mapping_The_Galaxy%2C_Language_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math
import matplotlib.pyplot as plt
# Some magick you will need in every program of the Course
# This will load some functionality you will need later

In [0]:
3+3

6

In [0]:
2**4

16

In [0]:
2.453-1e3

-997.547

In [0]:
# This is like a calculator
3*(4+2.3)/2-5**(5+2)

-78115.55

In [0]:
# The # sign means to ignore the stuff after the # sign 
# So you can write here anything 

# Part 2

In [0]:
# You can assign values to names (variables)
x=22
y=3

In [0]:
x+3

25

In [0]:
z=x*y+32.6

In [0]:
z

38.6

In [0]:
# You can print variables, or any calculation
print (x+3, z)
print (66)

25 38.6
66


After running the lines, you can return and change the values/code and rerun them

# Part 3

In [0]:
# What happens if something goes wrong
# For example I print the variable  that does not exist
print(qq)

NameError: ignored

In [0]:
### Or if divide by zero
1/0

ZeroDivisionError: ignored

If the problem happens (you see an exception), you can just fix the issue and rerun the cell

# Part 4

In [0]:
# You can have also variables that are strings
# They are written with double quotes or single quotes

In [0]:
print("hello")

hello


In [0]:
sx="I am x"
sy='I am y'
print (sx)

I am x


In [0]:
print (sy)

I am y


# **Part 5**

In [0]:
# Some mathematical functions
# The full list is here https://docs.scipy.org/doc/numpy/reference/

In [0]:
print (np.sin(3.))

0.1411200080598672


In [0]:
print (np.sqrt(2), np.cos(4), np.tan(5), np.arctan(4), np.deg2rad(60), np.rad2deg(1), np.arcsin(0.1))
# Square root, cosine, tangent, arctangent, degrees to radians, radians to degrees, arcsin

1.4142135623730951 -0.6536436208636119 -3.380515006246586 1.3258176636680326 1.0471975511965976 57.29577951308232


In [0]:
print (np.round(2.2), np.exp(4), np.log(55), np.log10(100))
# rounding, exponent, natural logarithm, log base 10

2.0 54.598150033144236 4.007333185232471 2.0


In [0]:
print (np.rad2deg(np.arctan2(np.sqrt(3),1)))

59.99999999999999


# Part 6

In [0]:
# The great thing about Python are arrays !
# They are like table columns
ax = np.array([1.,2,3,4,5])
print (ax)

[1. 2. 3. 4. 5.]


In [0]:
# You can work with arrays like with numbers
# The operations will be applied per element
bx = np.array([-5,-3,0,2,1])
print (2+ax*3 + bx*4)

[-15.  -4.  11.  22.  21.]


In [0]:
# we can apply any mathematical functions to them
print (np.sin(ax))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [0]:
print(ax**bx)

[ 1.     0.125  1.    16.     5.   ]


# **Part 7**

In [0]:
# You can create an array filled with zeros or ones
az = np.ones(10)
bz = np.zeros(3)
print (az)
print (bz)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0.]


In [0]:
# You can do operations only with array of the same legth
az+bz

ValueError: ignored

In [0]:
# You can Sum or compute the product of the whole array
tz = np.array([5,7,8])
print(np.sum(tz))
print(np.prod(tz))

20
280


In [0]:
# Minimum and maximum
print(np.min(tz),np.max(tz))

5 8


# Part 8

In [0]:
# you Can access individual elements (starting from zero)
q=np.array([10,20,12,-1.])
print (q[0],q[1],q[3])

10.0 20.0 -1.0


In [0]:
# You can find the location of maximal/minimal element
print (np.argmax(q),np.argmin(q))

1 3


In [75]:
# Subscripting
# You can use arrays to select subsets
x = np.array([1,2,3,4,5,6,7,8])
y = 1-x
subset = (x>3) & (x<7) 
# This is the definition of the subset 
print (x[subset])
yy = y[subset]
print (yy)

[4 5 6]
[-3 -4 -5]
